import {useEffect,useRef,useState} from "react";
import {useSearchParams,useParams} from "react-router-dom";
import {useLocale} from "../context/LocaleContext";
import {useCase} from "../context/CaseContext";
import {api,appMode,browserSha256,currentSession,waitForJob} from "../lib/api";
import {CaseSnapshot,CaseNode,loadSnapshot,loadCases,rankNodes,downloadProtected} from "../lib/caseData";
import InvestigationGraph from "../components/InvestigationGraph";
import LeafletMap from "../components/LeafletMap";
import {GraphNode,GraphEdge,EntityType} from "../data/dummy";

type Props={mode:string;onNavigate:(page:string,param?:string)=>void};
export default function CaseWorkspace({mode,onNavigate}:Props) {
  const {locale}=useLocale();const {caseId,selectCase}=useCase();const L=(en:string,hi:string)=>locale==="hi"?hi:en;
  const {personId}=useParams();
  const [data,setData]=useState<CaseSnapshot|null>(null);const [cases,setCases]=useState<Array<{id:string;title:string;title_hi?:string}>>([]);
  const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);
  const [selected,setSelected]=useState<CaseNode|null>(null);const [html,setHtml]=useState("");const [params,setParams]=useSearchParams();const intake=useRef<HTMLInputElement>(null);
  const filter=params.get("filter")||"all";const search=params.get("q")||"";
  const tabs=[["case-detail","Overview","सारांश"],["evidence","Evidence","साक्ष्य"],["graph","Graph","ग्राफ़"],["timeline","Timeline","घटनाक्रम"],["map","Map","मानचित्र"],["network","Network","नेटवर्क"],["financial","Financial","वित्तीय"],["reports","Reports","रिपोर्ट"]];
  useEffect(()=>{let active=true;setData(null);setSelected(null);setError("");loadSnapshot(caseId).then(result=>{if(active)setData(result);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[caseId,revision]);
  useEffect(()=>{loadCases().then(setCases).catch(()=>setCases([]));},[revision]);
  useEffect(()=>{if(personId&&data)setSelected(data.nodes.find(n=>n.id===personId)||null);},[personId,data]);
  useEffect(()=>{if(mode!=="reports")return;let active=true;setHtml("");(appMode==="full"?api.reportPreview(caseId,locale).then(r=>r.html):fetch(`/demo/${caseId==="CASE-X007"?"northbridge":"nightfall"}-report-${locale}.html`).then(r=>{if(!r.ok)throw new Error("Report preview unavailable.");return r.text();})).then(value=>{if(active)setHtml(value);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[mode,caseId,locale,revision]);
  function changeParam(key:string,value:string){setParams(p=>{p.set(key,value);return p;});}
  async function upload(file?:File){if(!file)return;setBusy(true);setMessage("");try{if(file.size>100*1024*1024)throw new Error(L("100 MB evidence limit.","साक्ष्य सीमा 100 MB है।"));if(appMode==="full"){const saved=await api.uploadEvidence(caseId,file);onNavigate("evidence-detail",saved.id);}else{const hash=await browserSha256(file);setMessage(`${L("Browser-only SHA-256; local secure service required to persist or analyze.","ब्राउज़र SHA-256; सहेजने या विश्लेषण के लिए स्थानीय सुरक्षित सेवा आवश्यक है।")} ${hash}`);}}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);if(intake.current)intake.current.value="";}}
  async function generate(){setBusy(true);setMessage("");try{if(appMode==="full"){const job=await api.generateReport(caseId,locale);const result=await waitForJob(job.jobId,status=>setMessage(`${L("Report job","रिपोर्ट कार्य")}: ${status} · ${job.jobId}`));await downloadProtected(api.downloadUrl(result.downloadUrl),`${caseId}-${locale}.pdf`);setRevision(n=>n+1);}else{await downloadProtected(`/demo/${caseId==="CASE-X007"?"northbridge":"nightfall"}-report-${locale}.pdf`,`${caseId}-${locale}.pdf`);}setMessage(L("PDF downloaded. Human review is required.","PDF डाउनलोड हुआ। मानव समीक्षा आवश्यक है।"));}catch(e){setMessage(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  async function reset(){if(!window.confirm(L("Reset demo database and graph? Immutable chain history is retained.","डेमो डेटाबेस और ग्राफ़ रीसेट करें? ब्लॉकचेन इतिहास बना रहेगा।")))return;setBusy(true);try{await api.resetDemo();selectCase("CASE-2026-017");onNavigate("case-detail","CASE-2026-017");setRevision(n=>n+1);setMessage(L("Demo reset. Sign in again if your refresh session was revoked.","डेमो रीसेट हुआ। आवश्यक हो तो दोबारा साइन इन करें।"));}catch(e){setMessage(String(e));}finally{setBusy(false);}}
  function citations(ids:string[]){return <div className="flex flex-wrap gap-2 mt-2">{ids.map(id=><button key={id} className="gov-chip text-[10px] font-mono" onClick={()=>onNavigate("evidence-detail",id)}>{id}</button>)}</div>;}
  const title=data?(locale==="hi"?data.case.title_hi||data.case.title:data.case.title):caseId;
  const visibleNodes=data?.nodes.filter(n=>(filter==="all"||n.type.toLowerCase()===filter)&&(!search||`${n.label} ${n.labelHi} ${n.id}`.toLowerCase().includes(search.toLowerCase())))||[];
  const graphNodes:GraphNode[]=visibleNodes.map((n,i)=>({id:n.id,label:locale==="hi"?n.labelHi||n.label:n.label,type:n.type.toLowerCase() as EntityType,x:110+(i%4)*175,y:110+Math.floor(i/4)*140,data:{...n.properties,evidenceCount:n.evidenceIds.length}}));
  const graphEdges:GraphEdge[]=(data?.edges||[]).map(e=>({...e,label:e.type})).filter(e=>visibleNodes.some(n=>n.id===e.source)&&visibleNodes.some(n=>n.id===e.target));
  const events=(data?.timeline||[]).filter(e=>filter==="all"||e.type.toLowerCase()===filter);
  const locationGroups=new Map<string,{id:string;name:string;lat:number;lng:number;type:string;entity:string;description:string;evidenceIds:string[]}>();
  for(const e of events){if(e.location?.lat==null||e.location.lng==null)continue;const key=`${e.location.lat},${e.location.lng}`;const title=locale==="hi"?e.titleHi||e.title:e.title;const previous=locationGroups.get(key);
    if(previous){previous.description+=`\n${title}`;previous.evidenceIds=[...new Set([...previous.evidenceIds,...e.evidenceIds])];}
    else locationGroups.set(key,{id:e.id,name:e.location.name,lat:e.location.lat,lng:e.location.lng,type:"primary",entity:e.entityIds[0]||"",description:title,evidenceIds:e.evidenceIds});
  }
  const locations=[...locationGroups.values()];
  return <div className="min-h-screen bg-[var(--color-base-bg)]">
    <header className="bg-[var(--color-primary)] text-white p-6"><div className="max-w-[1400px] mx-auto flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-xs text-white/65">{caseId} · DECYPHER BY EPOCH</p><h1 className="text-3xl !text-white mt-2">{title}</h1><p className="text-sm text-white/75 mt-2">{L("Fictional evidence intelligence • human review required","काल्पनिक साक्ष्य जाँच • मानव समीक्षा आवश्यक")}</p></div><label className="text-sm">{L("Selected case","चयनित केस")}<select aria-label={L("Selected case","चयनित केस")} value={caseId} className="block mt-2 p-2 bg-white text-[var(--color-primary)] min-w-[240px]" onChange={e=>{selectCase(e.target.value);onNavigate("case-detail",e.target.value);}}>{cases.map(c=><option key={c.id} value={c.id}>{locale==="hi"?c.title_hi||c.title:c.title}</option>)}</select></label></div></header>
    <nav aria-label={L("Case sections","केस अनुभाग")} className="bg-[var(--color-surface)] border-b border-[var(--color-border-subtle)] px-6"><div className="max-w-[1400px] mx-auto flex gap-2 overflow-x-auto py-3">{tabs.map(([page,en,hi])=><button key={page} aria-current={mode===page?"page":undefined} className={`gov-chip whitespace-nowrap ${mode===page?"is-active":""}`} onClick={()=>onNavigate(page,page==="case-detail"?caseId:undefined)}>{L(en,hi)}</button>)}</div></nav>
    <main className="max-w-[1400px] mx-auto p-6 space-y-5">
      <div className="gov-panel p-3 text-sm border-l-4 border-l-[var(--color-saffron)]">{appMode==="full"?L("Connected mode: service failures are shown, not replaced by dummy case data.","कनेक्टेड मोड: सेवा त्रुटियाँ स्पष्ट दिखती हैं, नकली डेटा नहीं।"):L("Public showcase: curated synthetic story. Local secure service required for writes and blockchain operations.","सार्वजनिक प्रदर्शन: काल्पनिक कहानी। सहेजने और ब्लॉकचेन के लिए स्थानीय सेवा आवश्यक है।")}</div>
      {message&&<div role="status" className="gov-panel p-4 text-sm break-all">{message}<button aria-label={L("Dismiss message","संदेश हटाएँ")} className="float-right ml-3" onClick={()=>setMessage("")}>×</button></div>}
      {error?<div role="alert" className="gov-panel p-8"><p>{error}</p><button className="btn-premium-outline mt-4" onClick={()=>setRevision(n=>n+1)}>{L("Retry","पुनः प्रयास")}</button></div>:!data?<div role="status" className="gov-panel p-8">{L("Loading case records…","केस रिकॉर्ड लोड हो रहे हैं…")}</div>:<>
        {mode==="case-detail"&&<>
          <section className="gov-panel p-6"><h2 className="text-xl mb-3">{L("Investigation brief","जाँच सारांश")}</h2><p>{locale==="hi"?data.case.description_hi||data.case.description:data.case.description}</p><p className="text-sm text-[var(--color-text-muted)] mt-3">{data.case.lead_investigator}</p></section>
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[["evidence",data.evidence.length,"Evidence","साक्ष्य"],["graph",data.nodes.length,"Entities","इकाइयाँ"],["timeline",data.timeline.length,"Events","घटनाएँ"],["network",data.edges.length,"Relationships","संबंध"]].map(([page,count,en,hi])=><button key={String(page)} className="gov-panel p-6 text-left" onClick={()=>onNavigate(String(page))}><p className="text-3xl font-mono">{count}</p><p className="text-sm mt-2">{L(String(en),String(hi))}</p></button>)}</div>
          <section className="gov-panel p-6"><h2 className="text-xl">{L("Evidence-backed leads","साक्ष्य-समर्थित संकेत")}</h2>{data.alerts.length?data.alerts.map(a=><article key={a.id} className="border-b border-[var(--color-border-subtle)] py-4"><p className="font-semibold">{L(a.title,"स्रोत साक्ष्य की समीक्षा आवश्यक")}</p><p className="text-sm mt-1">{L(a.reason,"यह समीक्षा संकेत है। मूल साक्ष्य देखें; यह दोष का निष्कर्ष नहीं है।")}</p>{citations(a.evidenceIds)}</article>):<p className="text-sm mt-3">{L("No evidence-backed alerts yet.","अभी कोई साक्ष्य-समर्थित संकेत नहीं है।")}</p>}</section>
          {appMode==="full"&&currentSession()?.role==="admin"&&<button className="btn-premium-outline" disabled={busy} onClick={reset}>{L("Reset demo (admin)","डेमो रीसेट (एडमिन)")}</button>}
        </>}
        {mode==="evidence"&&<>
          <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl">{L("Evidence library","साक्ष्य सूची")}</h2><input ref={intake} type="file" className="hidden" onChange={e=>upload(e.target.files?.[0])}/><button className="btn-premium" disabled={busy} onClick={()=>intake.current?.click()}>{busy?L("Processing…","प्रक्रिया जारी…"):L("Upload / hash evidence","साक्ष्य अपलोड / हैश")}</button></div>
          <div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();upload(e.dataTransfer.files[0]);}} className="border-2 border-dashed border-[var(--color-border-strong)] p-5 text-sm">{L("Drop a supported document, CSV, image, audio or MP4 here • 100 MB maximum.","दस्तावेज़, CSV, चित्र, ऑडियो या MP4 यहाँ छोड़ें • अधिकतम 100 MB।")}</div>
          <label className="block text-sm">{L("Search evidence","साक्ष्य खोजें")}<input className="gov-input block mt-2 w-full" value={search} onChange={e=>changeParam("q",e.target.value)}/></label>
          {data.evidence.filter(e=>`${e.id} ${e.name}`.toLowerCase().includes(search.toLowerCase())).map(e=><button key={e.id} className="gov-panel p-5 w-full text-left hover:border-[var(--color-primary)]" onClick={()=>onNavigate("evidence-detail",e.id)}><p className="font-mono text-xs">{e.id} · {e.mime_type} · {(e.size/1024).toFixed(1)} KB</p><h3 className="font-semibold mt-2">{e.name}</h3><p className="font-mono text-[10px] break-all mt-2">SHA-256 {e.sha256}</p></button>)}
          {!data.evidence.length&&<p className="gov-panel p-8">{L("No evidence yet. Upload the first artifact.","अभी कोई साक्ष्य नहीं है। पहला नमूना अपलोड करें।")}</p>}
        </>}
        {(mode==="graph"||mode==="entities")&&<>
          <div className="flex flex-wrap gap-3"><label className="text-sm">{L("Entity filter","इकाई फ़िल्टर")}<select className="gov-input ml-2" value={filter} onChange={e=>changeParam("filter",e.target.value)}>{["all","person","phone","vehicle","location","account","case"].map(type=><option key={type} value={type}>{type.toUpperCase()}</option>)}</select></label><input aria-label={L("Search entities","इकाइयाँ खोजें")} placeholder={L("Search entities","इकाइयाँ खोजें")} className="gov-input" value={search} onChange={e=>changeParam("q",e.target.value)}/></div>
          <div className="grid lg:grid-cols-[1fr_330px] gap-5"><section className="gov-panel overflow-hidden"><InvestigationGraph caption={`${caseId} / ${title}`} key={`${caseId}-${graphNodes.map(n=>n.id).join()}`} nodes={graphNodes} edges={graphEdges} height={600} onNodeClick={n=>setSelected(data.nodes.find(node=>node.id===n.id)||null)}/></section><aside className="gov-panel p-5"><h2 className="font-semibold">{selected?(locale==="hi"?selected.labelHi||selected.label:selected.label):L("Entity inspector","इकाई विवरण")}</h2>{selected?<><p className="font-mono text-xs mt-2">{selected.id} · {selected.type}</p><pre className="text-xs whitespace-pre-wrap break-all p-3 mt-3 bg-[var(--color-surface-2)]">{JSON.stringify(selected.properties,null,2)}</pre>{citations(selected.evidenceIds)}{data.edges.filter(e=>e.source===selected.id||e.target===selected.id).map(e=><article key={e.id} className="py-3 border-b border-[var(--color-border-subtle)]"><p className="font-mono text-xs break-all">{e.source} → {e.type} → {e.target}</p><p className="text-xs mt-1">{Math.round(e.confidence*100)}% · {e.timestamp}</p>{citations(e.evidenceIds)}</article>)}</>:<><p className="text-sm mt-3">{L("Select a labelled node to inspect properties, direction, confidence and supporting evidence.","गुण, दिशा, विश्वास और साक्ष्य देखने के लिए इकाई चुनें।")}</p>{visibleNodes.map(n=><button key={n.id} className="block underline text-sm mt-3" onClick={()=>setSelected(n)}>{locale==="hi"?n.labelHi||n.label:n.label}</button>)}</>}</aside></div>
          {!data.nodes.length&&<p>{L("Analysis has not created entities yet.","विश्लेषण ने अभी इकाइयाँ नहीं बनाई हैं।")}</p>}
        </>}
        {(mode==="timeline"||mode==="financial")&&<>
          <label className="text-sm">{L("Event filter","घटना फ़िल्टर")}<select className="gov-input ml-2" value={filter} onChange={e=>changeParam("filter",e.target.value)}>{["all","call","transaction","sighting","cross_case"].map(type=><option key={type} value={type}>{type.toUpperCase()}</option>)}</select></label>
          {events.filter(e=>mode!=="financial"||e.type==="TRANSACTION").map(e=><article key={e.id} className="gov-panel p-5"><p className="text-xs font-mono">{new Date(e.timestamp).toLocaleString(locale==="hi"?"hi-IN":"en-IN",{timeZone:"Asia/Kolkata"})} IST · {Math.round(e.confidence*100)}%</p><h3 className="font-semibold mt-2">{locale==="hi"?e.titleHi||e.title:e.title}</h3><p className="text-sm mt-2">{e.location?.name}</p>{citations(e.evidenceIds)}</article>)}
          {!events.filter(e=>mode!=="financial"||e.type==="TRANSACTION").length&&<p className="gov-panel p-6">{L("No matching timestamped evidence events.","कोई मेल खाती समयांकित साक्ष्य घटना नहीं है।")}</p>}
        </>}
        {mode==="map"&&<div className="grid lg:grid-cols-[1fr_330px] gap-5"><section className="gov-panel p-2"><LeafletMap key={caseId} height={600} showConnections={false} locations={locations} onEvidenceClick={id=>onNavigate("evidence-detail",id)}/></section><aside className="space-y-3">{events.filter(e=>e.location?.lat!=null).map(e=><article key={e.id} className="gov-panel p-4"><h3>{e.location?.name}</h3><p className="text-xs mt-2">{locale==="hi"?e.titleHi||e.title:e.title}</p>{citations(e.evidenceIds)}</article>)}{!locations.length&&<p className="gov-panel p-5">{L("No evidence-backed coordinates yet. Basemap is for orientation only.","अभी साक्ष्य-समर्थित निर्देशांक नहीं हैं। मानचित्र केवल संदर्भ है।")}</p>}</aside></div>}
        {mode==="network"&&<section className="gov-panel p-6"><h2 className="text-xl">{L("Connection ranking","संबंध क्रम")}</h2><p className="text-sm mt-2 mb-4">{L("Degree counts help prioritize human review, not predict guilt. CASE nodes indicate evidence-backed cross-case references.","संबंध संख्या मानव समीक्षा में मदद करती है, दोष का अनुमान नहीं। CASE इकाइयाँ साक्ष्य-समर्थित दूसरे केस के संदर्भ हैं।")}</p>{rankNodes(data).map(n=><article key={n.id} className="py-3 border-b border-[var(--color-border-subtle)]"><div className="flex justify-between gap-3"><button className="underline text-left" onClick={()=>{onNavigate("graph");setSelected(n);}}>{locale==="hi"?n.labelHi||n.label:n.label}</button><span className="font-mono">{n.degree} · {L("links","संबंध")}</span></div>{citations(n.evidenceIds)}</article>)}</section>}
        {mode==="reports"&&<><div className="flex justify-between flex-wrap gap-3"><h2 className="text-xl">{L("Investigation report preview","जाँच रिपोर्ट पूर्वावलोकन")}</h2><button className="btn-premium" disabled={busy||(appMode==="full"&&currentSession()?.role==="forensics")} title={currentSession()?.role==="forensics"?L("Investigator, supervisor or admin role required","जाँचकर्ता, पर्यवेक्षक या एडमिन भूमिका आवश्यक"):undefined} onClick={generate}>{L("Generate & download PDF","PDF बनाएँ और डाउनलोड करें")}</button></div><iframe title={L("Report preview","रिपोर्ट पूर्वावलोकन")} srcDoc={html} sandbox="" className="w-full h-[750px] bg-white border border-[var(--color-border-subtle)]"/><section className="gov-panel p-5"><h2>{L("Report history","रिपोर्ट इतिहास")}</h2>{data.reports.map(r=><button key={r.id} className="block underline text-sm mt-3" onClick={()=>downloadProtected(api.downloadUrl(r.downloadUrl),`${caseId}-${r.locale}.pdf`).catch(e=>setMessage(e.message))}>{r.id} · {r.locale.toUpperCase()} · {r.createdAt}</button>)}{!data.reports.length&&<p className="text-sm mt-3">{L("No generated local reports yet. Showcase files are static synthetic reports.","अभी कोई स्थानीय रिपोर्ट नहीं बनी है। प्रदर्शन फ़ाइलें स्थिर काल्पनिक रिपोर्ट हैं।")}</p>}</section></>}
      </>}
    </main>
  </div>;
}
