import {useLocale} from "../context/LocaleContext";
export default function PublicPortal({page="landing",onNavigate}:{page?:string;onNavigate:(page:string)=>void}) {
  const {locale}=useLocale();const L=(en:string,hi:string)=>locale==="hi"?hi:en;
  const titles:Record<string,[string,string]>={landing:["Evidence connected. Integrity visible.","जुड़ा साक्ष्य। स्पष्ट अखंडता।"],capabilities:["Investigation capabilities","जाँच क्षमताएँ"],"how-it-works":["From artifact to accountable insight","साक्ष्य से उत्तरदायी जानकारी तक"],security:["Security with honest boundaries","स्पष्ट सीमाओं वाली सुरक्षा"],about:["Decypher by Epoch","डिसाइफ़र बाय एपॉक"],terms:["Terms and disclaimer","शर्तें और अस्वीकरण"],privacy:["Privacy and accessibility","गोपनीयता और सुगम्यता"]};
  const [en,hi]=titles[page]||titles.landing;
  const sections:Record<string,Array<[string,string,string,string]>>={
    capabilities:[["Evidence provenance","साक्ष्य का मूल","Real SHA-256 hashing, secure local object storage, custody records and a real local blockchain registry.","वास्तविक SHA-256 हैश, स्थानीय वस्तु संग्रह, अभिरक्षा रिकॉर्ड और स्थानीय ब्लॉकचेन रजिस्ट्री।"],["Connected investigation","जुड़ी जाँच","Case-scoped graph, timestamped events, map coordinates and resolvable evidence citations.","केस-आधारित ग्राफ़, समयांकित घटनाएँ, मानचित्र निर्देशांक और खुलने वाले साक्ष्य संदर्भ।"],["Human-reviewed reports","मानव-समीक्षित रिपोर्ट","English/Hindi previews and PDFs. Analytical leads never establish guilt.","अंग्रेज़ी / हिंदी पूर्वावलोकन और PDF। जाँच संकेत दोष सिद्ध नहीं करते।"]],
    "how-it-works":[["01 • Collect and hash","01 • संग्रह और हैश","Upload a supported artifact, preserve its bytes and record its SHA-256 identity.","समर्थित फ़ाइल अपलोड करें, मूल बाइट सुरक्षित रखें और SHA-256 पहचान दर्ज करें।"],["02 • Register and analyze","02 • पंजीकरण और विश्लेषण","Authorized personnel anchor hashes on Hardhat. A worker derives deterministic, cited findings.","अधिकृत व्यक्ति Hardhat पर हैश दर्ज करते हैं। कार्यकर्ता नियत, साक्ष्य-संदर्भित विवरण बनाता है।"],["03 • Inspect, verify, report","03 • निरीक्षण, सत्यापन, रिपोर्ट","Explore relationships, compare hashes against the live contract and export a human-review report.","संबंध देखें, लाइव अनुबंध से हैश मिलाएँ और मानव-समीक्षा रिपोर्ट डाउनलोड करें।"]],
    security:[["Role-based access","भूमिका-आधारित पहुँच","JWT authentication and server-side role checks protect the local API. Demo passwords and keys are not production credentials.","JWT प्रमाणीकरण और सर्वर भूमिका जाँच स्थानीय API सुरक्षित करती हैं। डेमो पासवर्ड और कुंजियाँ उत्पादन के लिए नहीं हैं।"],["Integrity is not truth","अखंडता सत्य नहीं है","A hash match proves byte identity, not factual accuracy, legality or guilt. Human review is mandatory.","हैश मेल बाइट की पहचान सिद्ध करता है, तथ्य, वैधता या दोष नहीं। मानव समीक्षा अनिवार्य है।"],["Prototype boundaries","प्रदर्शन की सीमाएँ","Production MFA, key management, forensic certification and advanced computer vision are not represented as complete.","उत्पादन MFA, कुंजी प्रबंधन, फॉरेंसिक प्रमाणन और उन्नत कंप्यूटर विज़न पूर्ण होने का दावा नहीं है।"]],
    about:[["One coherent story","एक जुड़ी कहानी","Operation Nightfall is a fictional Delhi NCR investigation connecting communications, vehicle metadata, transfers and a Northbridge case reference.","ऑपरेशन नाइटफॉल काल्पनिक दिल्ली एनसीआर जाँच है जो संचार, वाहन विवरण, धन हस्तांतरण और नॉर्थब्रिज संदर्भ जोड़ती है।"],["Built for demonstration","प्रदर्शन के लिए निर्मित","Decypher by Epoch is not an official government service. All demo people, records and media are synthetic.","डिसाइफ़र बाय एपॉक आधिकारिक सरकारी सेवा नहीं है। सभी डेमो व्यक्ति, रिकॉर्ड और मीडिया काल्पनिक हैं।"]],
    terms:[["Demonstration use only","केवल प्रदर्शन उपयोग","Do not upload real sensitive evidence to the public showcase. The local stack is a prototype, not a certified forensic system.","सार्वजनिक प्रदर्शन में वास्तविक संवेदनशील साक्ष्य अपलोड न करें। स्थानीय स्टैक प्रमाणित फॉरेंसिक प्रणाली नहीं है।"],["Copyright and responsibility","कॉपीराइट और उत्तरदायित्व","Synthetic artifacts illustrate provenance. Users retain responsibility for authorization, legal compliance and independent review.","काल्पनिक फ़ाइलें मूल रिकॉर्ड की प्रक्रिया दिखाती हैं। अनुमति, कानून पालन और स्वतंत्र समीक्षा उपयोगकर्ता का उत्तरदायित्व है।"]],
    privacy:[["Local and public modes","स्थानीय और सार्वजनिक मोड","Showcase hashing runs in your browser without uploading the selected file. Full mode stores evidence in your configured local service.","प्रदर्शन हैश ब्राउज़र में बनता है; चुनी फ़ाइल अपलोड नहीं होती। पूर्ण मोड आपके स्थानीय संग्रह में फ़ाइल सहेजता है।"],["Accessibility","सुगम्यता","Keyboard navigation, named controls, high contrast, text sizing and persistent English/Hindi selection are provided. Report source text is retained for citation accuracy.","कीबोर्ड नेविगेशन, नामित नियंत्रण, उच्च कंट्रास्ट, पाठ आकार और स्थायी भाषा चयन उपलब्ध हैं। सही संदर्भ के लिए मूल स्रोत पाठ रखा जाता है।"]],
  };
  return <div><section className="bg-[var(--color-primary)] text-white py-16 px-6"><div className="max-w-[1200px] mx-auto grid lg:grid-cols-[1.2fr_.8fr] gap-12 items-center"><div><p className="font-mono text-xs tracking-[.18em] text-white/65">DECYPHER BY EPOCH • {L("FICTIONAL PROTOTYPE","काल्पनिक प्रदर्शन")}</p><h1 className="text-5xl !text-white mt-5 leading-tight">{L(en,hi)}</h1><p className="text-lg text-white/75 mt-6">{L("One reviewable trail from source evidence to connected findings. No fake blockchain confirmations. No conclusions of guilt.","मूल साक्ष्य से जुड़े विवरण तक एक समीक्षायोग्य क्रम। कोई नकली ब्लॉकचेन पुष्टि नहीं। दोष का निष्कर्ष नहीं।")}</p><div className="flex flex-wrap gap-3 mt-7"><button className="btn-premium" onClick={()=>onNavigate("login")}>{L("Explore the investigation","जाँच देखें")}</button><button className="btn-premium-outline !text-white !border-white/40" onClick={()=>onNavigate(page==="landing"?"how-it-works":"landing")}>{L(page==="landing"?"See the workflow":"Back to home",page==="landing"?"कार्यप्रणाली देखें":"मुखपृष्ठ पर लौटें")}</button></div></div>{page==="landing"&&<div className="border border-white/25 p-8"><p className="font-mono text-xs text-white/60">CASE-2026-017</p><h2 className="!text-white text-3xl mt-3">{L("Operation Nightfall","ऑपरेशन नाइटफॉल")}</h2><div className="space-y-5 mt-7">{[["CDR → communications","CDR → संचार"],["CCTV metadata → location","CCTV विवरण → स्थान"],["CSV → financial trail","CSV → वित्तीय क्रम"],["Field note → cross-case bridge","नोट → दूसरे केस का संबंध"]].map(([a,b],i)=><p key={a} className="border-l-2 border-[var(--color-saffron)] pl-4 text-white/80"><span className="font-mono mr-3">0{i+1}</span>{L(a,b)}</p>)}</div></div>}</div></section><main className="max-w-[1200px] mx-auto p-6 py-10 grid md:grid-cols-3 gap-5">{(sections[page]||sections.capabilities).map(([title,titleHi,text,textHi])=><article key={title} className="gov-panel p-6"><h2 className="text-xl">{L(title,titleHi)}</h2><p className="text-sm mt-4 text-[var(--color-text-secondary)]">{L(text,textHi)}</p></article>)}</main></div>;
}
