import {useEffect,useRef,useState} from "react";
import {useLocale} from "../context/LocaleContext";
import {useCase} from "../context/CaseContext";
import {api,appMode} from "../lib/api";
import {caseAnswer,loadSnapshot} from "../lib/caseData";
type Message={text:string;user?:boolean;citations?:string[];confidence?:number;reasoning?:string};
export default function CopilotWidget({onNavigate}:{onNavigate:(page:string,param?:string)=>void}) {
  const {locale}=useLocale();const {caseId}=useCase();const L=(en:string,hi:string)=>locale==="hi"?hi:en;
  const [open,setOpen]=useState(false);const [input,setInput]=useState("");const [busy,setBusy]=useState(false);const [messages,setMessages]=useState<Message[]>([]);
  const generation=useRef(0);
  useEffect(()=>{generation.current++;setMessages([]);setInput("");setBusy(false);return()=>{generation.current++;};},[caseId]);
  async function send(question=input){if(!question.trim()||busy)return;const request=generation.current;setInput("");setBusy(true);setMessages(m=>[...m,{text:question,user:true}]);try{const result=appMode==="full"?await api.copilot(caseId,question,locale):caseAnswer(await loadSnapshot(caseId),question,locale);if(request===generation.current)setMessages(m=>[...m,{text:result.answer,citations:result.citations,confidence:result.confidence,reasoning:result.reasoning}]);}catch(e){if(request===generation.current)setMessages(m=>[...m,{text:e instanceof Error?e.message:String(e),confidence:0}]);}finally{if(request===generation.current)setBusy(false);}}
  return <><button className="fixed bottom-5 right-5 z-50 btn-premium" aria-expanded={open} aria-label={L(open?"Close Copilot":"Open Copilot",open?"सहायक बंद करें":"सहायक खोलें")} onClick={()=>setOpen(!open)}>{L("Copilot","सहायक")}</button>{open&&<aside role="dialog" aria-label={L("Evidence-grounded Copilot","साक्ष्य-आधारित सहायक")} className="fixed bottom-20 right-4 z-50 gov-panel w-[min(390px,calc(100vw-32px))] h-[min(550px,75vh)] flex flex-col"><header className="p-4 border-b border-[var(--color-border-subtle)]"><h2 className="font-semibold">{L("Decypher Copilot","डिसाइफ़र सहायक")}</h2><p className="font-mono text-xs mt-1">{caseId}</p><p className="text-xs mt-2">{L("Deterministic answers with citations. Human review required.","साक्ष्य-संदर्भ सहित नियत उत्तर। मानव समीक्षा आवश्यक।")}</p></header><div aria-live="polite" className="overflow-y-auto flex-1 p-4 space-y-4">{!messages.length&&<p className="text-sm">{L("Ask about entities or evidence in the selected case.","चयनित केस की इकाइयों या साक्ष्य के बारे में पूछें।")}</p>}{messages.map((m,i)=><article key={i} className={`p-3 text-sm ${m.user?"bg-[var(--color-primary)] text-white":"bg-[var(--color-surface-2)]"}`}><p>{m.text}</p>{m.confidence!=null&&<p className="text-xs mt-2">{L("Confidence","विश्वास")}: {Math.round(m.confidence*100)}%</p>}{m.reasoning&&<p className="text-xs mt-2">{m.reasoning}</p>}<div className="flex flex-wrap gap-1 mt-2">{m.citations?.map(id=><button key={id} className="gov-chip font-mono text-[10px]" onClick={()=>{onNavigate("evidence-detail",id);setOpen(false);}}>{id}</button>)}</div></article>)}{busy&&<p role="status">{L("Checking case evidence…","केस साक्ष्य जाँचा जा रहा है…")}</p>}</div><div className="p-3 border-t border-[var(--color-border-subtle)] flex gap-2 flex-wrap">{[["Vikram Singh relationships","विक्रम सिंह के संबंध"],["Raj Mehta evidence","राज मेहता का साक्ष्य"],["Case summary","केस सारांश"]].map(([en,hi])=><button disabled={busy} key={en} className="gov-chip text-xs" onClick={()=>send(L(en,hi))}>{L(en,hi)}</button>)}</div><form className="p-3 flex gap-2 border-t border-[var(--color-border-subtle)]" onSubmit={e=>{e.preventDefault();send();}}><input aria-label={L("Copilot question","सहायक प्रश्न")} minLength={3} maxLength={1000} className="gov-input min-w-0 flex-1" value={input} onChange={e=>setInput(e.target.value)}/><button className="btn-premium btn-sm" disabled={busy||input.trim().length<3}>{L("Send","भेजें")}</button></form></aside>}</>;
}
