import {createHash} from "node:crypto";

export const locations = [
  ["Connaught Place",28.6315,77.2167],["Gurugram Warehouse",28.4595,77.0266],["Noida Sector 62",28.627,77.3723],
  ["Dwarka Sector 21",28.552,77.058],["Nehru Place",28.549,77.251],["Karol Bagh",28.651,77.19],
  ["Okhla Industrial Area",28.531,77.279],["Faridabad Sector 15",28.398,77.321],["Ghaziabad Depot",28.669,77.453],
  ["Greater Noida Logistics Park",28.474,77.504],["Lajpat Nagar",28.568,77.244],["Saket",28.524,77.206],
  ["Delhi Cantonment",28.597,77.136],["Rohini Sector 18",28.738,77.137],["Manesar Distribution Yard",28.354,76.939],
];
const names = ["Raj Mehta","Arjun Verma","Neha Kapoor","Vikram Singh","Maya Sethi","Priya Nair","Dev Rao","Zoya Khan","Aarav Bedi","Isha Malhotra","Kunal Sethi","Sana Qureshi","Kabir Anand","Rohan Das","Meera Joshi","Tara Bhatia","Nikhil Arora","Sameer Shah","Anika Bose","Farhan Ali","Riya Menon","Dhruv Saini","Leela Rao","Aditya Sen","Simran Gill","Varun Nanda","Ayesha Mir","Harsh Jain","Naina Roy","Yusuf Khan","Kavya Iyer","Manav Kapoor","Rehan Malik","Pooja Sood","Vihaan Sethi","Saira Ahmed","Akash Dutta","Disha Verma","Omar Siddiq","Sneha Pandey","Anirudh Bansal","Fatima Noor","Gautam Puri","Ira Saxena","Jatin Grover","Lavanya Shah","Mohit Yadav","Nadia Rizvi","Parth Mehra","Sonal Gupta"];
const stories = [
 ["NIGHTFALL","Operation Nightfall","ऑपरेशन नाइटफॉल","Consignment diversion","A fictional distributor reports that three consignments marked for Noida were dispatched to a Gurugram holding yard. Warehouse logs and ordinary supplier payments are interleaved with a disputed after-hours pickup.","The dispatch clerk recalls a white van at 20:15. The visitor ledger records a grey utility vehicle at 20:32; the clerk could not read its plate.","Preserve the original visitor ledger and obtain a second independent account before identifying an occupant."],
 ["NORTHBRIDGE","Operation Northbridge","ऑपरेशन नॉर्थब्रिज","Duplicate dispatch documents","A fictional courier audit finds two delivery receipts bearing the same reference but different arrival times. The inquiry tests whether this reflects a routine reprint, delayed synchronization or a substituted delivery.","The recipient remembers an early delivery. A gate supervisor describes a later vehicle arrival but did not inspect the parcel.","Compare source clocks and receipt revision history; the shared contact with Nightfall is only a review lead."],
 ["COPPER","Operation Copper Ledger","ऑपरेशन कॉपर लेजर","Supplier reconciliation","A fictional procurement team reports unmatched credit notes against copper-component invoices. Several large payments coincide with quarter-end settlement, so an amount threshold alone cannot determine improper activity.","The accounts assistant says the batch included two legitimate refunds. A purchasing note lists only one supporting credit reference.","Request refund authorizations and reconcile invoice totals before interpreting the payment pattern."],
 ["RIVER","Operation River Signal","ऑपरेशन रिवर सिग्नल","Missing equipment movements","A fictional service contractor cannot reconcile equipment movements between Dwarka and Faridabad. Communications include routine maintenance calls and a concentrated exchange before a depot handover.","A technician recalls returning the equipment on Monday. The receiving log was entered Tuesday and may record intake rather than occurrence.","Separate handover occurrence time from data-entry time and review the equipment serial inventory."],
 ["ORCHARD","Operation Orchard Route","ऑपरेशन ऑर्चर्ड रूट","Route exception review","A fictional cold-chain operator investigates repeated route exceptions around Ghaziabad. Most stops have valid service notes; two unsigned exceptions require corroboration from dispatch records.","The driver reports a road closure. The route planner says an alternative stop was authorized verbally but has no signed approval.","Check the original dispatch instructions; location proximity is not proof of vehicle presence."],
 ["MIRROR","Operation Mirror Exchange","ऑपरेशन मिरर एक्सचेंज","Reused beneficiary references","A fictional finance review finds a beneficiary reference reused across two vendors. Matching labels may reflect shared invoicing software rather than common ownership, and account codes remain explicitly synthetic.","The vendor representative describes a shared payment desk. The internal register lists separate authorized representatives.","Validate the relationship through source contracts; do not equate a reused reference with control or guilt."],
 ["HARBOR","Operation Harbor Receipt","ऑपरेशन हार्बर रिसीट","Return inventory review","A fictional returns center has six packages entered twice after a scanner outage. The inquiry examines a plausible synchronization explanation alongside an unresolved outbound movement.","A floor supervisor recalls a scanner restart. A temporary worker saw a pickup but cannot identify which carton was loaded.","Compare raw scan identifiers with the manually signed return sheets."],
 ["LANTERN","Operation Lantern Access","ऑपरेशन लैंटर्न एक्सेस","Access-card discrepancy","A fictional facilities team reviews after-hours access near a maintenance window. Shared shifts and copied logs complicate attribution; access authorization and physical presence are separate claims.","A guard recalls an authorized contractor. The maintenance roster lists a replacement technician whose sign-in was incomplete.","Obtain the roster revision and preserve original access exports without inferring identity from proximity."],
 ["SUMMIT","Operation Summit Voucher","ऑपरेशन समिट वाउचर","Expense supporting records","A fictional accounts team finds vouchers missing supporting travel notes. Several routine reimbursements provide negative controls, while a small subset has conflicting dates needing review.","An employee says a trip was rescheduled. The approval message shows the original date and does not document the revision.","Compare itinerary changes and authorization messages before classifying the expense."],
 ["EMBER","Operation Ember Transfer","ऑपरेशन एम्बर ट्रांसफर","Stock transfer reconciliation","A fictional parts depot reports a mismatch between a stock-transfer sheet and receiving count. Partial deliveries and unit-conversion differences are plausible alternatives to diversion.","The dispatch team counted sealed boxes. The recipient recorded individual units and noted one damaged seal without identifying an occupant.","Reconcile units and packaging, preserve the receiving sheet and seek independent seal observations."],
];
const roles=["dispatch coordinator","supplier representative","accounts reviewer","field witness","maintenance contractor"];
const sha=x=>createHash("sha256").update(x).digest("hex");
const at=(caseIndex,minutes)=>new Date(Date.UTC(2026,7,1+caseIndex,3,30)+minutes*60000).toISOString();
const split=rows=>[0,1,2].map(i=>rows.slice(Math.floor(i*rows.length/3),Math.floor((i+1)*rows.length/3)));

export function buildRichPlan(seed=20260915) {
  if(!Number.isSafeInteger(seed)||seed<0)throw new Error("Invalid seed");
  const ns=sha(`rich-${seed}`).slice(0,10),cases=[],evidence=[],links=[];
  let state=seed>>>0;const random=()=>{state=(1664525*state+1013904223)>>>0;return state/4294967296;};
  const allVehicles=Array.from({length:15},(_,i)=>`SYN-VEH-${String(i+1).padStart(3,"0")}`);
  stories.forEach(([code,title,titleHi,category,summary,conflict,nextStep],ci)=>{
    const id=`CASE-SYN-${ns}-${code}`,cast=names.slice(ci*5,ci*5+5),bridge=names[((ci+9)%10)*5+3];
    const places=[locations[ci],locations[(ci+5)%15],locations[(ci+10)%15]];
    const vehicle=allVehicles[ci],second=allVehicles[10+ci%5],org=`SYN ${code.toLowerCase()} Services`,account=`SYN-${code}-01`,shared=`SYN-${stories[(ci+9)%10][0]}-02`;
    const created=at(ci,20*1440),ids={};
    const c={id,case_number:`SYN-RICH/${seed}/${code}`,title:`${title} - Source Review`,title_hi:`${titleHi} - स्रोत समीक्षा`,description:`${summary} Current uncertainty: ${conflict} Next review: ${nextStep} All records are fictional.`,description_hi:"यह पूरी तरह काल्पनिक जाँच है। स्रोत समय, वैकल्पिक स्पष्टीकरण और विरोधी बयान अलग-अलग दर्ज हैं। कोई निष्कर्ष दोष सिद्ध नहीं करता।",priority:["critical","high","medium","low"][ci%4],status:ci===8?"closed":ci===6?"pending":"active",lead_investigator:["Investigator Aditi Rao","Supervisor Prakash Verma","Forensic Analyst Sana Khan"][ci%3],created_at:created,category,cast,bridge,places:places.map(p=>p[0]),vehicles:[vehicle,second],organization:org,openQuestions:[conflict,nextStep]};cases.push(c);
    const add=(tag,mime,extra)=>{const ext={"text/csv":"csv","text/plain":"txt","image/png":"png","audio/wav":"wav","video/mp4":"mp4","application/pdf":"pdf"}[mime];const eid=`EV-SYN-${ns}-${code}-${tag==="OBSERVATIONS"?"OBS":tag}`;ids[tag]=eid;evidence.push({id:eid,case_id:id,name:`${code.toLowerCase()}-${tag.toLowerCase()}.${ext}`,path:`artifacts/${code.toLowerCase()}/${tag.toLowerCase()}.${ext}`,mime_type:mime,created_at:created,description:`Fictional ${category}: ${tag.toLowerCase().replaceAll("-"," ")}. Source statements are reviewable claims, not findings of guilt.`,...extra});};
    const calls=Array.from({length:500},(_,ri)=>{const a=ci*5+ri%5,b=ci*5+(ri%5+1+Math.floor(random()*3))%5;return [`SYN-${ns}-${code}-C-${String(ri+1).padStart(4,"0")}`,`SYN-${String(a+1).padStart(10,"0")}`,`SYN-${String(b+1).padStart(10,"0")}`,at(ci,ri*12+(ri%17===0?2:0)),ri%19===0?0:20+Math.floor(random()*480),places[ri%3][0],ri%19===0?"Synthetic unanswered call. Tower label alone does not prove subscriber location.":"Synthetic routine dispatch/maintenance communication. Phone identities are defined only by the fictional source inventory."];});
    split(calls).forEach((rows,i)=>add(`CDR-${i+1}`,"text/csv",{recordKind:"call",headers:["record_id","caller","receiver","start_time","duration_seconds","tower_location","source_note"],rows}));
    const transfers=Array.from({length:150},(_,ri)=>[`SYN-${ns}-${code}-T-${String(ri+1).padStart(4,"0")}`,at(ci,6*1440+ri*35),cast[ri%5],ri%11===0?shared:ri%2?`SYN-${code}-02`:account,ri%37===0?245000:Math.round((850+random()*75000)*100)/100,ri%37===0?"Synthetic larger settlement; supporting invoice/refund authorization still requires review.":"Synthetic ordinary supplier settlement. INR amounts are invented."]);
    split(transfers).forEach((rows,i)=>add(`FIN-${i+1}`,"text/csv",{recordKind:"transfer",headers:["transaction_id","timestamp","from_entity","to_account","amount_inr","source_note"],rows}));
    const inventory=[];const inv=(name,type,props,hi="")=>inventory.push([name,type,hi,JSON.stringify({...props,synthetic:true}),"Explicitly authored fictional source inventory; not inferred recognition."]);
    cast.forEach((name,i)=>{inv(name,"PERSON",{role:roles[i],age_band:["25-34","35-44","45-54"][i%3],review_status:i===3?"witness statement requires corroboration":"source-named participant",occupation:roles[i]});inv(`+91 ${String(ci*5+i+1).padStart(10,"0")}`,"PHONE",{identifier_kind:"non-dialable fictional test code",ownership_basis:"explicit synthetic inventory"});});
    inv(bridge,"PERSON",{role:"source-named cross-case contact"});inv(vehicle,"VEHICLE",{make:"fictional compact van",color:"white",plate_kind:"non-registrable synthetic identifier"});inv(second,"VEHICLE",{make:"fictional utility vehicle",color:"grey",plate_kind:"non-registrable synthetic identifier"});inv(org,"ORG",{sector:"logistics/service support",registration:"SYN-ORG-DEMO",status:"fictional business"});
    inv(`A/C ending ${account}`,"ACCOUNT",{bank:"Synthetic Cooperative Bank",currency:"INR"});inv(`A/C ending SYN-${code}-02`,"ACCOUNT",{bank:"Synthetic Cooperative Bank",currency:"INR"});inv(`A/C ending ${shared}`,"ACCOUNT",{bank:"Synthetic Cooperative Bank",currency:"INR",review_note:"shared reference is not ownership proof"});places.forEach(([name,lat,lng])=>inv(name,"LOCATION",{lat,lng,coordinate_precision:"approximate neighborhood, not private address"}));
    add("INVENTORY","text/csv",{recordKind:"entity",headers:["canonical_name","entity_type","label_hi","properties_json","source_note"],rows:inventory});
    const observations=[];const obs=(a,ak,b,bk,rel,minute,note,confidence=.8)=>observations.push([`SYN-${ns}-${code}-O-${String(observations.length+1).padStart(3,"0")}`,at(ci,minute),a,ak,b,bk,rel,places[observations.length%3][0],confidence,note]);
    cast.forEach((p,i)=>{obs(p,"PERSON",`+91 ${String(ci*5+i+1).padStart(10,"0")}`,"PHONE","SOURCE_ASSIGNED_PHONE",60+i,`Explicit fictional inventory assignment for ${p}; it is not an inferred real subscriber identity.`);obs(p,"PERSON",org,"ORG","SOURCE_LISTED_ROLE",100+i,`${p} is listed as ${roles[i]} in the fictional source inventory.`);});
    obs(vehicle,"VEHICLE",places[0][0],"LOCATION","CAPTIONED_AT",8*1440+660,`Staged scene caption: ${vehicle} at ${places[0][0]}; human-authored, not computer vision.`,.85);
    obs(second,"VEHICLE",places[1][0],"LOCATION","CAPTIONED_AT",8*1440+677,`Alternative staged vehicle observation; occupancy is unknown.`,.65);
    obs(cast[3],"PERSON",vehicle,"VEHICLE","WITNESS_MENTION",8*1440+660,conflict,.6);
    obs(cast[4],"PERSON",second,"VEHICLE","ALTERNATIVE_ACCOUNT",8*1440+677,`An independent source gives a different time/vehicle: ${conflict}`,.65);
    obs(cast[0],"PERSON",bridge,"PERSON","SOURCE_MENTIONS_CONTACT",9*1440,`Source review names ${bridge} in another investigation. Shared identity is fictional; corroboration required.`,.75);
    obs(org,"ORG",`A/C ending ${account}`,"ACCOUNT","SOURCE_LISTED_ACCOUNT",6*1440,`Fictional supplier inventory names the account; not a verified legal ownership record.`);
    obs(cast[2],"PERSON",`A/C ending ${shared}`,"ACCOUNT","REVIEW_SHARED_REFERENCE",7*1440,`Cross-case account reference requires source-contract review.`,.7);
    obs(org,"ORG",places[2][0],"LOCATION","SOURCE_LISTED_DEPOT",5*1440,`Fictional depot record identifies a public neighborhood, not a private address.`);
    obs(vehicle,"VEHICLE",org,"ORG","SOURCE_DISPATCHED_FOR",8*1440+640,`Dispatch note lists ${vehicle}; it does not identify an occupant.`);
    obs(cast[1],"PERSON",places[1][0],"LOCATION","STATEMENT_MENTIONS",10*1440,`Source account mentions ${places[1][0]}; physical presence remains unverified.`,.6);
    add("OBSERVATIONS","text/csv",{recordKind:"observation",headers:["record_id","timestamp","source_entity","source_type","target_entity","target_type","relationship","location","confidence","source_note"],rows:observations});
    const notes=[
      ["INTAKE","Initial complaint",`${summary}\nReporting source: ${cast[0]}, ${roles[0]}. The source distinguishes observed facts from assumptions. No statutory offence or real complainant is asserted.`],
      ["WITNESS-A","Primary witness account",`${cast[3]} describes: ${conflict}\nThe witness did not read a plate and cannot reliably identify an occupant. Approximate occurrence: ${at(ci,8*1440+660)}. Recorded intake: ${created}.`],
      ["WITNESS-B","Independent account",`${cast[4]} recalls the alternative vehicle ${second} around ${at(ci,8*1440+677)}. This is an independent fictional account, not corroboration of every detail in Witness A. Clock offset and memory precision remain unresolved.`],
      ["LAB","Technical examination note",`Original source exports are preserved without alteration. Hashes are SHA-256 over exact bytes. Synthetic media captions/transcripts are supplied by the author; no OCR, vision or speech recognition is claimed. Byte integrity does not establish pre-intake truth.\nReview action: ${nextStep}`],
      ["CUSTODY","Synthetic handover ledger",`Collected by ${c.lead_investigator} at ${created}. Hashed at intake +1 second. Analyzed at +2 seconds. Fictional handover to Reviewer ${ci+1} at +10 minutes; reviewer returns to the same collecting custodian at +20 minutes. These are demo source statements, not recipient signatures.`],
      ["BRIDGE","Cross-case source review",`Source names ${bridge} and account ${shared}. Compare ${stories[(ci+9)%10][1]}. A common name/account reference is a lead, not evidence of common control. Supporting sources: ${ids.INVENTORY}, ${ids.OBSERVATIONS}, ${ids["FIN-1"]}.\n${nextStep}`],
      ["DISPATCH","Authored dispatch transcript",`Synthetic transcript, not machine transcription.\n${at(ci,8*1440+660)} Dispatcher: Please reconcile the receiving count at ${places[0][0]}.\n${at(ci,8*1440+661)} Reviewer: One time reference differs; keep both source accounts.\n${at(ci,8*1440+662)} Dispatcher: Do not identify an occupant from the staged scene alone.`],
    ];
    notes.forEach(([tag,heading,body])=>add(tag,"text/plain",{text:`SYNTHETIC EVIDENCE - NOT AN OFFICIAL RECORD\n${c.title}\nCase: ${id}\nSource: ${tag}\nRecorded: ${created}\n${heading}\n\n${body}\n\nहिंदी सारांश: यह काल्पनिक स्रोत रिकॉर्ड है। विरोधी बयान, समय और वैकल्पिक स्पष्टीकरण की समीक्षा आवश्यक है।\n`}));
    ["SCENE-A","SCENE-B"].forEach((tag,i)=>add(tag,"image/png",{asset:{kind:"scene",caseTitle:c.title,vehicle:i?second:vehicle,location:places[i][0],timestamp:at(ci,8*1440+660+i*17)}}));
    add("AUDIO","audio/wav",{asset:{kind:"audio",frequency:350+ci*27,transcriptEvidence:ids.DISPATCH}});
    add("CCTV","video/mp4",{asset:{kind:"video",caseTitle:c.title,vehicle,location:places[0][0],timestamp:at(ci,8*1440+660)}});
    add("DOSSIER","application/pdf",{asset:{kind:"dossier",caseTitle:c.title,summary,conflict,nextStep,caseId:id,lead:c.lead_investigator,recorded:created,sourceIds:[ids.INTAKE,ids["WITNESS-A"],ids["WITNESS-B"],ids.OBSERVATIONS]}});
    links.push({evidence_id:ids.BRIDGE,case_id:`CASE-SYN-${ns}-${stories[(ci+1)%10][0]}`});
  });
  return {formatVersion:1,fictional:true,profile:"realistic-v2",seed,cases,evidence,links,locations:locations.map(([name,lat,lng])=>({name,lat,lng})),expected:{cases:10,evidence:200,callRecords:5000,financialRecords:1500},coverage:{people:50,vehicles:15,accounts:20,organizations:10,locations:15,sourceObservations:200},demoQuestions:cases.map(c=>({case_id:c.id,questions:[`What evidence mentions ${c.cast[0]}?`,`Which sources mention ${c.bridge}?`,`What are the unresolved alternatives in ${c.title}?`]}))};
}
